CREATE TABLE WA2P_CATEGORIE (
	id char(5) PRIMARY KEY,
	nome varchar(30) NOT NULL
)TYPE=INNODB;

CREATE TABLE WA2P_UTENTI (
	nickname char(30) PRIMARY KEY,
	nome varchar(50) NOT NULL,
	cognome varchar(50) NOT NULL,
	email varchar(50) NOT NULL,
	pw varchar(50) NOT NULL
)TYPE=INNODB;

CREATE TABLE WA2P_ARTISTI (
	id char(5) PRIMARY KEY,
	nomeArte varchar(30) NOT NULL
)TYPE=INNODB;

CREATE TABLE WA2P_EVENTI (
	id char(10) PRIMARY KEY,
	titolo varchar(30) NOT NULL,
	luogo varchar(50) NOT NULL,
	data date,
	idU char(30),
	categoria char(5),
	FOREIGN KEY (idU) REFERENCES WA2P_UTENTI(nickname) ON UPDATE CASCADE ON DELETE NO ACTION,
	FOREIGN KEY (categoria) REFERENCES WA2P_CATEGORIE(id) ON UPDATE CASCADE ON DELETE NO ACTION
)TYPE=INNODB;

CREATE TABLE WA2P_COMMENTI (
	id char(8) PRIMARY KEY,
	commento varchar(100) NOT NULL,
	voto char(1) NOT NULL,
	idU char(30),
	evento char(30),
	FOREIGN KEY (idU) REFERENCES WA2P_UTENTI(nickname) ON UPDATE CASCADE ON DELETE NO ACTION,
	FOREIGN KEY (evento) REFERENCES WA2P_EVENTI(id) ON UPDATE CASCADE ON DELETE NO ACTION
)TYPE=INNODB;

CREATE TABLE WA2P_C_U (
	idU char(30),
	idC char(5), 
	PRIMARY KEY(idU,idC),
	FOREIGN KEY (idU) REFERENCES WA2P_UTENTI(nickname) ON UPDATE CASCADE ON DELETE NO ACTION,
	FOREIGN KEY (idC) REFERENCES WA2P_CATEGORIE(id) ON UPDATE CASCADE ON DELETE NO ACTION
)TYPE=INNODB;

CREATE TABLE WA2P_E_A (
	idA char(5),
	idE char(10),
	PRIMARY KEY(idA,idE),
	FOREIGN KEY (idA) REFERENCES WA2P_ARTISTI(id) ON UPDATE CASCADE ON DELETE NO ACTION,
	FOREIGN KEY (idE) REFERENCES WA2P_EVENTI(id) ON UPDATE CASCADE ON DELETE NO ACTION
)TYPE=INNODB;


